### ISSUE TITLE
chore(deps): fix pyupgrade and refurb Python 3.14 incompatibility

### ISSUE THREAD

**Issue by Geoffe-Ga** [Geoffe-Ga/start_green_stay_green#281]
## Summary

The pre-commit hooks `pyupgrade` and `refurb` both fail on Python 3.14 with tool-internal errors, making them no-ops during local pre-commit runs.

### pyupgrade
\`\`\`
TypeError: cannot use a bytes pattern on a string-like object
  File ".../pyupgrade/_main.py", line 297, in _fix_tokens
    tokenize.cookie_re.match(token.src)
\`\`\`

This is a known upstream issue: `tokenize.cookie_re` became bytes-only in Python 3.14.

### refurb
\`\`\`
AttributeError: 'Options' object has no attribute 'allow_redefinition' and no __dict__ for setting new attributes.
Did you mean: 'allow_redefinition_new'?
  File ".../refurb/main.py", line 164, in run_refurb
    opt.allow_redefinition = True
\`\`\`

This is a refurb incompatibility with newer mypy that renamed `allow_redefinition` → `allow_redefinition_new`.

## Impact

- Both hooks silently "pass" in CI on Python 3.11/3.12 (where they work)
- Both hooks fail noisily when running `pre-commit run --all-files` locally on Python 3.14
- Contributors using Python 3.14 locally cannot distinguish real failures from these broken hooks

## Proposal

Options:
1. Pin pyupgrade / refurb to versions that work on both 3.11 and 3.14
2. Upgrade to newer versions if/when they fix the compat issue
3. Temporarily disable the hooks on Python 3.14 via `language_version` pin
4. Skip these hooks with `SKIP=pyupgrade,refurb` in dev docs

## Acceptance Criteria

- [ ] `pre-commit run --all-files` passes cleanly on Python 3.14
- [ ] pyupgrade and refurb still run where they work (CI on 3.11/3.12)

## Context

Encountered during #268, #269, #270 development. Every pre-commit run showed these failures. Originally ignored as "pre-existing" but they're blocking max-quality development experience on Python 3.14.

**Comment by Geoffe-Ga** [comment]
Resolved by PR #290 — `fix(deps): upgrade pyupgrade and refurb for Python 3.14 compatibility (#281)` (commit `f62fbd6`). Both pre-commit hooks now run cleanly on Python 3.11, 3.12, and 3.14 — the `tokenize.cookie_re` bytes-only change and the mypy `allow_redefinition` → `allow_redefinition_new` rename are both addressed.

Closes via PR #290.

---
_Generated by [Claude Code](https://claude.ai/code)_
